kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rhdh-dynamic-plugins-root
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
